//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginFramework.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0}.
        /// </summary>
        internal static string AddedPlugin {
            get {
                return ResourceManager.GetString("AddedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added plugin directory {0}.
        /// </summary>
        internal static string AddedPluginDirectory {
            get {
                return ResourceManager.GetString("AddedPluginDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly added {0}.
        /// </summary>
        internal static string AssemblyAdded {
            get {
                return ResourceManager.GetString("AssemblyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly already added.
        /// </summary>
        internal static string AssemblyAlreadyAdded {
            get {
                return ResourceManager.GetString("AssemblyAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly fetched {0} ({1} bytes read from {2}).
        /// </summary>
        internal static string AssemblyFetchedBytesRead {
            get {
                return ResourceManager.GetString("AssemblyFetchedBytesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly removed {0}.
        /// </summary>
        internal static string AssemblyRemoved {
            get {
                return ResourceManager.GetString("AssemblyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created inside AppDomain: {0}.
        /// </summary>
        internal static string CreatedInsideAppDomain {
            get {
                return ResourceManager.GetString("CreatedInsideAppDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created plugin {0}.
        /// </summary>
        internal static string CreatedPlugin {
            get {
                return ResourceManager.GetString("CreatedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory already added.
        /// </summary>
        internal static string DirectoryAlreadyAdded {
            get {
                return ResourceManager.GetString("DirectoryAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist.
        /// </summary>
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while fetching {0} ({1}) {2}).
        /// </summary>
        internal static string ExceptionWhileFetching {
            get {
                return ResourceManager.GetString("ExceptionWhileFetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch {0}, assembly not known..
        /// </summary>
        internal static string FetchErrorAssemblyNotKnown {
            get {
                return ResourceManager.GetString("FetchErrorAssemblyNotKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch {0}, file not found in these locations:.
        /// </summary>
        internal static string FetchErrorFileNotFoundIn {
            get {
                return ResourceManager.GetString("FetchErrorFileNotFoundIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileFound {0}.
        /// </summary>
        internal static string FileFound {
            get {
                return ResourceManager.GetString("FileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} locked.
        /// </summary>
        internal static string FileLocked {
            get {
                return ResourceManager.GetString("FileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileLost {0}.
        /// </summary>
        internal static string FileLost {
            get {
                return ResourceManager.GetString("FileLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exists, awaiting Deleted event.
        /// </summary>
        internal static string FileNotExistAwaitingDeleteEvent {
            get {
                return ResourceManager.GetString("FileNotExistAwaitingDeleteEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} plugins in {1}.
        /// </summary>
        internal static string FoundCountPluginsIn {
            get {
                return ResourceManager.GetString("FoundCountPluginsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got Deleted before Created was Raised. Ignoring file {0}.
        /// </summary>
        internal static string GotDeleteBeforeEmitCreatedIgnoringFile {
            get {
                return ResourceManager.GetString("GotDeleteBeforeEmitCreatedIgnoringFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost {0} plugins when {1} was removed.
        /// </summary>
        internal static string LostCountPluginsWhenAssemblyRemoved {
            get {
                return ResourceManager.GetString("LostCountPluginsWhenAssemblyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnChanged {0}.
        /// </summary>
        internal static string OnChanged {
            get {
                return ResourceManager.GetString("OnChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnCreated {0}.
        /// </summary>
        internal static string OnCreated {
            get {
                return ResourceManager.GetString("OnCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnDeleted {0}.
        /// </summary>
        internal static string OnDeleted {
            get {
                return ResourceManager.GetString("OnDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnRenamed {0} -&gt; {1}.
        /// </summary>
        internal static string OnRenamed {
            get {
                return ResourceManager.GetString("OnRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op must be And or Or.
        /// </summary>
        internal static string OpMustBeAndOrOr {
            get {
                return ResourceManager.GetString("OpMustBeAndOrOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queueing {0} for {1}.
        /// </summary>
        internal static string QueueingEventForFile {
            get {
                return ResourceManager.GetString("QueueingEventForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raising {0} for {1}.
        /// </summary>
        internal static string RaisingEventFor {
            get {
                return ResourceManager.GetString("RaisingEventFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0}.
        /// </summary>
        internal static string RemovedPlugin {
            get {
                return ResourceManager.GetString("RemovedPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed plugin directory {0}.
        /// </summary>
        internal static string RemovedPluginDirectory {
            get {
                return ResourceManager.GetString("RemovedPluginDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required setting {0} not supplied while creating {1}.
        /// </summary>
        internal static string RequiredSettingNotSuppliedOnCreate {
            get {
                return ResourceManager.GetString("RequiredSettingNotSuppliedOnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning plugins for {0}.
        /// </summary>
        internal static string ReturningPluginsFor {
            get {
                return ResourceManager.GetString("ReturningPluginsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source added {0}.
        /// </summary>
        internal static string SourceAdded {
            get {
                return ResourceManager.GetString("SourceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source already added.
        /// </summary>
        internal static string SourceAlreadyAdded {
            get {
                return ResourceManager.GetString("SourceAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source removed {0}.
        /// </summary>
        internal static string SourceRemoved {
            get {
                return ResourceManager.GetString("SourceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown assembly.
        /// </summary>
        internal static string UnknownAssembly {
            get {
                return ResourceManager.GetString("UnknownAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown directory.
        /// </summary>
        internal static string UnknownDirectory {
            get {
                return ResourceManager.GetString("UnknownDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown EventType {0}.
        /// </summary>
        internal static string UnknownEventType {
            get {
                return ResourceManager.GetString("UnknownEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown source.
        /// </summary>
        internal static string UnknownSource {
            get {
                return ResourceManager.GetString("UnknownSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version string must be on format intMajor.intMinor.
        /// </summary>
        internal static string VersionStringFormatError {
            get {
                return ResourceManager.GetString("VersionStringFormatError", resourceCulture);
            }
        }
    }
}
